apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgABSBt2GsRk/NmtQDK17kfny1JwtMoSQ2r4njcsUTrf0XydGyl5YF7H7G0PF/jy+bn0wT+dPAdEmuJbClTx6iH1wcWRv3iGGMw4G1rznY4yErrgpFHRBO6FMq/OYQ/TBnHw0Ap/U6EXifCHXq5dFT0eYaBRNpRiodCLI7Hk2Y53HofdYIpN7zlhc2EmEW4/4UuugxS51BTJbMxGnbbmMcXwnSvxt3ZBdkm/uCrL4oM94gEvidGD4KCbQ4aYEQnDOuMLFgO3ZgL6BwCl/rnWUUGRkPf7EIkn57mT29O/tI2A00BzHjvIW2QZEE6+dhobx32arpiAZI027U71Itl4pT1AZuYBZ3UNS84o/QW14BsS3FOKMh5sZG+3oma3VpvomvTFEmfGEo8Ioeq2gZox2ZCztp0izckX2GGcdkDEo34+HgqxpMUSAzcSIlPZgs0VxrXajgca/dx+vG59i+y+zWqVW5xKOXfDqSfW5UrMx+MCZRZ4YBeQnO5JNe9fU60FYetfgSJFaywG0DZd99TrfBzwNJnZ2hZqqDbQUd8Jjed3/hRL1WZexKl8/+eVYgeMzXUNmsfS2gLbOCLBy01qBwN6nzHa6ZrM/qdB47bZA7Vp0KJ2TFxMOmlSd6onNdI0jvQBmXDW2az/h75Uopf2bZ+yPATVLMP0ludp5wiiM5zF/vyQZZHUWhZxhqblFogGeFQcplUudRCsnTNc+PSw6GgjTWQihtRP0GwAznlDpdJ9mNBIfOl18clw
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
