version: 2

builds:
  - main: ./cmd/kue
    binary: kue
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Archisman-Mridha/kue/cmd/kue/version.Version={{ .Tag }}
      - -X github.com/Archisman-Mridha/kue/cmd/kue/version.Commit={{ .ShortCommit }}
      - -X github.com/Archisman-Mridha/kue/cmd/kue/version.Date={{ .Date }}
dist: build/goreleaser

upx:
  - enabled: true

archives:
  - formats: [tar.gz]

    # This name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Use zip for windows archives.
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  disable: true
