apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  source:
    repoURL: {{ .RepoURL }}
    targetRevision: HEAD
    path: {{ .KueProjectPath }}/renderred/development/resources/argocd
    directory:
      recurse: true

  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
