package kue

#HelmInstallation: {
	repoURL: string
	chartPath: string
	version: string

  releaseName: string

	namespace: string
	createNamespace: bool | *true

	// A concrete CueLang struct type will be generated by Kue.
	//
	// First a values.schema.json file for the corresponding Helm chart needs to be generated. And
	// then that JSON schema file will be imported to CueLang using the `cue import jsonschema`
	// command.
	values: {...}
}
