apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  source:
    repoURL: https://github.com/Archisman-Mridha/kue
    targetRevision: HEAD
    path: e2e/manifests/renderred/production/resources/certManager
    directory:
      recurse: true

  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
